name: PAT-Reusable-Workflow

on:
  push:
  workflow_call: 

jobs:
    print-secret:
        runs-on: self-hosted
        steps:
            - name: step1
              run: |
                if [ -z "${{ secrets.MYPAT }}" ]; then
                    echo "Secret is empty or not passed correctly"
                else
                    echo "Secret is set"
                fi