name: PAT-Reusable-Workflow

on:
  push:  
  workflow_call:
    secrets: inherit

jobs:
    print-secret:
        runs-on: self-hosted
        steps:
            - name: step1
              run: echo ${{ secrets.MYPAT }}