name: PAT-Reusable-Workflow

on:
  #push:  
  workflow_call:
    secrets:
      MYPAT:
        required: true

jobs:
    print-secret:
        runs-on: self-hosted
        steps:
            - name: Use outputs from reusable workflow
              run: | 
                echo "Calling GitHub API with reusable flow"
                curl -L \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: token ${{ secrets.MYPAT }}" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  https://api.github.com/users/rjain997/repos
